//! Public entry points and function emission. `renderFlowZig` /
//! `renderFlowFile` turn a parsed `flow_io.Flow` into a complete `.zig`
//! file: file header + component imports + module-scope `var`s, the
//! entry event `pub fn`, and one `fn` per transitively-referenced
//! subgraph (RFC §6). Also hosts the per-function header / return-type /
//! param helpers and the up-front collision / entity / component-type
//! validators.

const std = @import("std");
const flow_io = @import("../flow_io.zig");
const errors = @import("errors.zig");
const registries = @import("registries.zig");
const cycles = @import("cycles.zig");
const pins = @import("pins.zig");
const graph = @import("graph.zig");
const scope = @import("scope.zig");
const text = @import("text.zig");

const CodegenError = errors.CodegenError;
const Options = registries.Options;
const FlowRegistry = registries.FlowRegistry;
const CustomNodeRegistry = registries.CustomNodeRegistry;
const GraphContext = graph.GraphContext;
const sanitizeSymbol = pins.sanitizeSymbol;
const collectOutputs = pins.collectOutputs;
const anyOutput = pins.anyOutput;
const delaySubflowNode = pins.delaySubflowNode;
const assertNoOutputCollision = pins.assertNoOutputCollision;
const detectReferenceCycleFlow = cycles.detectReferenceCycleFlow;
const emitBody = scope.emitBody;
const indentBlock = text.indentBlock;
const mentionsIdent = text.mentionsIdent;
const countByte = text.countByte;

const components_import_path_fmt = "../../components/{s}.zig";

/// Render a single flow as a Zig source file. When the flow references
/// subgraphs, prefer `renderFlowFile` — this entry point emits no
/// subgraph functions and treats a `Subflow` node as `UnknownFlowRef`
/// unless an empty registry happens to suffice.
pub fn renderFlowZig(
    allocator: std.mem.Allocator,
    flow: flow_io.Flow,
    options: Options,
) (CodegenError || FlowRegistry.RegistryError || std.mem.Allocator.Error || std.Io.Writer.Error)![]u8 {
    var registry = FlowRegistry.init(allocator);
    defer registry.deinit();
    return renderFlowFile(allocator, flow, &registry, options);
}

/// Render `entry` as a Zig file: its event `pub fn`, plus a `fn` for
/// every flow transitively reachable through `Subflow` nodes (RFC §6).
/// `registry` resolves those references. Caller owns the returned bytes.
pub fn renderFlowFile(
    allocator: std.mem.Allocator,
    entry: flow_io.Flow,
    registry: *const FlowRegistry,
    options: Options,
) (CodegenError || std.mem.Allocator.Error || std.Io.Writer.Error)![]u8 {
    // RFC §4: cycle check runs before any emission, rooted at the
    // entry flow itself — so cycles are rejected even when the entry
    // is unnamed or not registered ("caught regardless of which flow
    // is the build entry point").
    {
        var chain: ?[]const u8 = null;
        detectReferenceCycleFlow(allocator, registry, entry, entry.name, &chain) catch |err| {
            if (chain) |c| allocator.free(c);
            return err;
        };
        if (chain) |c| allocator.free(c);
    }

    // Collect the transitive set of referenced subgraphs.
    var subgraphs: std.ArrayList(flow_io.Flow) = .empty;
    defer subgraphs.deinit(allocator);
    var seen = std.StringHashMap(void).init(allocator);
    defer seen.deinit();
    try collectSubgraphs(allocator, registry, entry, &subgraphs, &seen);

    // Distinct effective names that sanitize to the same identifier
    // would emit colliding `fn` definitions — reject up front (RFC §6
    // assumes symbols don't collide; `sanitizeSymbol` is lossy). The
    // entry `pub fn` name (`onCall` / `setup`) is checked too: a
    // subgraph whose name sanitizes to one of those would emit a `fn`
    // colliding with the file's `pub fn`.
    try assertNoSymbolCollision(allocator, entryFunctionName(entry.event), subgraphs.items);

    // Each flow's declared `params` must not collide (after
    // sanitization) with each other or the fixed `fn` params —
    // checked for the entry flow and every referenced subgraph. The
    // entry reserves its lifecycle arg; a subgraph does not.
    try assertNoParamCollision(allocator, entry);
    for (subgraphs.items) |sg| try assertNoParamCollision(allocator, sg);

    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    const w = &aw.writer;

    // File header.
    try w.writeAll("//! Generated by labelle-gui codegen — DO NOT EDIT.\n");
    try w.writeAll("//! Source: ");
    try w.print("{f}", .{std.zig.fmtString(options.flow_name)});
    try w.writeAll(".flow.jsonc\n\n");
    try w.writeAll("const std = @import(\"std\");\n");
    try w.writeAll("const game_mod = @import(\"game\");\n");
    try w.writeAll("const Game = game_mod.Game;\n");
    try w.writeAll("const EntityId = game_mod.EntityId;\n");

    // Component imports — union across the entry flow and all
    // referenced subgraphs, de-duplicated, sorted (issue #101).
    const component_types = try collectComponentTypesAll(allocator, entry, subgraphs.items);
    defer allocator.free(component_types);
    for (component_types) |type_name| {
        try w.print(
            "const {s} = @import(\"" ++ components_import_path_fmt ++ "\").{s};\n",
            .{ type_name, type_name, type_name },
        );
    }
    try w.writeAll("\n");

    // File-scope `var` declarations (RFC-FLOW-VOCABULARY §4 —
    // variables). One `pub var <name>: <type> = <default>;` per
    // declared entry. Scoped to this flow's emitted `.zig` module
    // (persistent across handler invocations); declared `pub` so
    // integration tests and the eventual global-variables story
    // (project-wide `variables/` folder generating cross-flow `pub
    // var`s) share one shape. Codegen never emits `@import("…")` of
    // another flow's variables, so the RFC's "invisible to other
    // flows" constraint holds at the codegen layer.
    if (entry.variables.len != 0) {
        for (entry.variables) |v| {
            try w.print("pub var {s}: {s} = {s};\n", .{ v.name, v.type, v.default.zig_text });
        }
        try w.writeAll("\n");
    }

    // File-scope growable collections (flow-codegen#24). One `pub var`
    // per declared entry — game-allocator-backed, game-lifetime. A LIST
    // is `std.ArrayList(<element>)`; a MAP is
    // `std.AutoHashMapUnmanaged(<key>, <value>)`. `.empty` is the
    // zero-init (no allocator needed); ops allocate on demand through
    // `game.allocator`. There is NO auto-deinit in v1: collections live
    // for the game's lifetime and are reclaimed by the OS at exit (proper
    // deinit-on-teardown is a follow-up).
    if (entry.collections.len != 0) {
        for (entry.collections) |c| {
            switch (c.kind) {
                .list => try w.print("pub var {s}: std.ArrayList({s}) = .empty;\n", .{ c.name, c.element }),
                .map => try w.print("pub var {s}: std.AutoHashMapUnmanaged({s}, {s}) = .empty;\n", .{ c.name, c.key, c.value }),
            }
        }
        try w.writeAll("\n");
    }

    // Per-node persistent gate state for `Once`/`Cooldown` exec-gates
    // (flow-codegen#47). One module-level `pub var` per gate node, keyed by
    // (flow, node id) — the single-output exec-gates carry their state at
    // module scope (persistent across handler invocations) exactly like the
    // `variables`/`collections` blocks above, NOT as on-node payload:
    //   `Once`     → `pub var __once_<flowfn>_n<id>: bool = false;`
    //   `Cooldown` → `pub var __cd_<flowfn>_n<id>: f64 = -1e18;` (sentinel so
    //                the gate opens on first entry).
    // The `__` prefix is RESERVED for generated state. Node ids are unique
    // only WITHIN a flow (every flow's ids start at 1), so the var name is
    // namespaced by `<flowfn>` — the flow's sanitized function-name
    // identifier (entry → `entryFunctionName`, subgraph → `sanitizeSymbol`),
    // which `assertNoSymbolCollision` already guarantees is unique across the
    // entry function and every subgraph function. With the `<flowfn>` prefix
    // the names are collision-free WITHOUT cross-flow dedup: distinct flows
    // get distinct prefixes, and ids don't repeat within one flow. The
    // lowering side (`emitGate` in `scope.zig`) reads the SAME `<flowfn>` off
    // `ctx.flow_fn`, so the two sites produce byte-identical names. Gates can
    // live in the entry flow OR any referenced subgraph (both render through
    // `emitBody`), so the pass scans both.
    {
        var emitted_any = false;
        var flow_idx: usize = 0;
        while (flow_idx <= subgraphs.items.len) : (flow_idx += 1) {
            const f = if (flow_idx == 0) entry else subgraphs.items[flow_idx - 1];
            const flow_fn = try gateFlowFn(allocator, f, flow_idx == 0);
            defer allocator.free(flow_fn);
            for (f.nodes) |n| {
                switch (n.kind) {
                    .Once => {
                        try w.print("pub var __once_{s}_n{d}: bool = false;\n", .{ flow_fn, n.id });
                        emitted_any = true;
                    },
                    .Cooldown => {
                        try w.print("pub var __cd_{s}_n{d}: f64 = -1e18;\n", .{ flow_fn, n.id });
                        emitted_any = true;
                    },
                    else => {},
                }
            }
        }
        if (emitted_any) try w.writeAll("\n");
    }

    // Per-Delay deferred-subflow state for `Delay` exec nodes
    // (flow-codegen#48). One capture struct + one trampoline `fn` per Delay
    // node, namespaced by `<flowfn>` exactly like the gate state above —
    // node ids are unique only WITHIN a flow, so the `<flowfn>` prefix keeps
    // the names collision-free across the entry function and every subgraph
    // (the same guarantee `assertNoSymbolCollision` proves). A Delay's
    // capture struct FIELDS are the deferred Subflow's declared input params
    // (names + types, read from the registry); its trampoline casts the
    // type-erased game/ctx pointers back to `*Game` / the typed capture and
    // calls the subflow with the snapshotted args. Gates and Delays can live
    // in the entry flow OR any referenced subgraph (both render through
    // `emitBody`), so the pass scans both. The lowering side (`emitDelay` in
    // `scope.zig`) reads the SAME `<flowfn>` off `ctx.flow_fn`, so the
    // emission and call sites produce byte-identical names.
    {
        var emitted_any = false;
        var flow_idx: usize = 0;
        while (flow_idx <= subgraphs.items.len) : (flow_idx += 1) {
            const f = if (flow_idx == 0) entry else subgraphs.items[flow_idx - 1];
            const flow_fn = try gateFlowFn(allocator, f, flow_idx == 0);
            defer allocator.free(flow_fn);
            for (f.nodes) |n| {
                if (n.kind != .Delay) continue;
                try emitDelayState(allocator, w, f, registry, flow_fn, n);
                emitted_any = true;
            }
        }
        if (emitted_any) try w.writeAll("\n");
    }

    // Fallible-FlowNode error-policy adapters (flow-codegen#27). Emit the
    // `__flowCommand` / `__flowReport` comptime helpers only when this file
    // actually lowers a `CustomNode` (any command or reporter) — the
    // lowering routes every plugin `impl` call through them so an error
    // union in the impl compiles under a defined policy instead of tripping
    // a raw Zig "unhandled error" compile error.
    {
        var needs_helpers = false;
        var flow_idx: usize = 0;
        while (flow_idx <= subgraphs.items.len) : (flow_idx += 1) {
            const f = if (flow_idx == 0) entry else subgraphs.items[flow_idx - 1];
            for (f.nodes) |n| {
                if (n.kind == .CustomNode) {
                    needs_helpers = true;
                    break;
                }
            }
            if (needs_helpers) break;
        }
        if (needs_helpers) try emitFallibleFlowNodeHelpers(w);
    }

    // Entry flow → its event `pub fn`.
    try renderEntryFunction(allocator, w, entry, registry, options.custom_nodes, options.flow_name);

    // Subgraphs → one `fn` each (RFC §6).
    for (subgraphs.items) |sg| {
        try w.writeAll("\n");
        try renderSubgraphFunction(allocator, w, sg, registry, options.custom_nodes);
    }

    return aw.toOwnedSlice();
}

/// Depth-first collect of every flow reachable through `Subflow`
/// nodes, excluding `entry` itself. Order is deterministic
/// (discovery order). Assumes the cycle check already passed.
fn collectSubgraphs(
    allocator: std.mem.Allocator,
    registry: *const FlowRegistry,
    flow: flow_io.Flow,
    out: *std.ArrayList(flow_io.Flow),
    seen: *std.StringHashMap(void),
) (CodegenError || std.mem.Allocator.Error)!void {
    for (flow.nodes) |n| {
        if (n.kind != .Subflow) continue;
        const ref_name = n.kind.Subflow.flow;
        if (seen.contains(ref_name)) continue;
        const ref = registry.get(ref_name) orelse return error.UnknownFlowRef;
        try seen.put(ref_name, {});
        try out.append(allocator, ref);
        try collectSubgraphs(allocator, registry, ref, out, seen);
    }
}

/// Emit the comptime error-policy adapters a fallible `CustomNode`
/// lowering routes through (flow-codegen#27). flow-codegen can't see the
/// impl's return type (it works off a string registry), so the fallible/
/// non-fallible decision is deferred to the generated file's own compile
/// via these adapters:
///
///   * `__flowCommand` — a `!void` command's error is logged and swallowed
///     (best-effort, mirroring the `ListAppend` `catch {}` precedent); a
///     plain `void` impl is called directly (the error branch is
///     comptime-eliminated).
///   * `__flowReport` — a `!T` reporter fails fast (`std.debug.panic`):
///     there is no value to feed the downstream pins, and the generated
///     handlers are not fallible, so `try`-propagation isn't available. A
///     plain `T` impl is called directly. `__FlowNodePayload` computes the
///     helper's return type — the error union's payload, or the type itself.
///
/// The `__` prefix is reserved for generated symbols. The adapters are
/// `inline`, so the indirection costs nothing at runtime.
fn emitFallibleFlowNodeHelpers(w: *std.Io.Writer) std.Io.Writer.Error!void {
    try w.writeAll(
        \\// Fallible FlowNode error policy (flow-codegen#27).
        \\fn __FlowNodePayload(comptime f: anytype) type {
        \\    const R = @typeInfo(@TypeOf(f)).@"fn".return_type.?;
        \\    return switch (@typeInfo(R)) {
        \\        .error_union => |eu| eu.payload,
        \\        else => R,
        \\    };
        \\}
        \\inline fn __flowCommand(comptime f: anytype, args: anytype) void {
        \\    if (@typeInfo(@typeInfo(@TypeOf(f)).@"fn".return_type.?) == .error_union) {
        \\        @call(.auto, f, args) catch |__err|
        \\            std.log.scoped(.flow).err("flow command node failed: {s}", .{@errorName(__err)});
        \\    } else {
        \\        @call(.auto, f, args);
        \\    }
        \\}
        \\inline fn __flowReport(comptime f: anytype, args: anytype) __FlowNodePayload(f) {
        \\    if (@typeInfo(@typeInfo(@TypeOf(f)).@"fn".return_type.?) == .error_union) {
        \\        return @call(.auto, f, args) catch |__err|
        \\            std.debug.panic("flow reporter node failed: {s}", .{@errorName(__err)});
        \\    } else {
        \\        return @call(.auto, f, args);
        \\    }
        \\}
        \\
        \\
    );
}

// =====================================================================
// Function emission
// =====================================================================

fn renderEntryFunction(
    allocator: std.mem.Allocator,
    w: *std.Io.Writer,
    flow: flow_io.Flow,
    registry: *const FlowRegistry,
    custom_nodes: ?*const CustomNodeRegistry,
    flow_name: []const u8,
) (CodegenError || std.mem.Allocator.Error || std.Io.Writer.Error)!void {
    // An `OnEvent` flow has a different shape from the lifecycle events
    // — a plugin-callback handler plus a `setup` that installs it —
    // so it has its own renderer.
    if (flow.event == .OnEvent)
        return renderEventEntry(allocator, w, flow, registry, custom_nodes, flow_name);

    var ctx = try GraphContext.init(allocator, flow, registry, custom_nodes);
    defer ctx.deinit();
    // Gate-state vars in this entry flow are namespaced by the entry
    // function name (`onCall`/`setup`) — see `gateFlowFn` / `emitGate`.
    ctx.flow_fn = entryFunctionName(flow.event);

    // A `.subgraph` entry is a subgraph in its own right (RFC §3/§6) —
    // it has no `entity` in scope, only declared `params`. An
    // entity-scoped node (`GetComponent` / `SetField`) here must wire
    // its `entity` input pin (RFC-PLUGIN-EVENTS §9); an unwired one
    // would emit a read of an undefined `entity`. The check is
    // per-node so a flow can mix wired and unwired entity-scoped
    // nodes freely.
    //
    // Post-Phase 6 (RFC-FLOW-VOCABULARY): the lifecycle event-header
    // path is gone — every flow that previously bound a lifecycle
    // `entity` identifier now reads `payload.entity` through a wired
    // `Identifier` node, so `.subgraph` is the only entry-function path
    // through here.
    try assertEntityAvailable(flow);

    // A `.subgraph` flow used as the file entry point is a subgraph in
    // its own right (RFC §3/§6): its `Output` nodes form the return
    // value, exactly as for a referenced subgraph.
    const entry_fn = entryFunctionName(flow.event);
    const outputs = try collectOutputs(allocator, flow);
    defer allocator.free(outputs);

    // Distinct Output names sanitizing to one identifier would emit a
    // result struct with duplicate fields — reject up front.
    try assertNoOutputCollision(allocator, outputs);

    // Multi-output entry returns a named result struct (RFC §6).
    if (outputs.len > 1) {
        try w.print("const {s}_Result = struct {{\n", .{entry_fn});
        for (outputs) |o| {
            const field = try sanitizeSymbol(allocator, o.kind.Output.name);
            defer allocator.free(field);
            try w.print("    {s}: {s},\n", .{ field, o.kind.Output.type });
        }
        try w.writeAll("};\n");
    }

    try writeFnHeader(allocator, w, flow, outputs);

    // Render the body into a buffer first, so we can see whether `game`
    // is actually referenced. Zig rejects *both* an unused parameter
    // and a pointless `_ = x;` discard of a used one — so it is
    // discarded only when the body never mentions it.
    var body_aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer body_aw.deinit();
    const bw = &body_aw.writer;

    try emitBody(allocator, bw, &ctx, flow_name, true);

    // Return statement for a subgraph entry with declared Outputs.
    if (outputs.len == 1) {
        const expr = (try ctx.resolveInput(allocator, outputs[0], "value")) orelse return error.DanglingPin;
        defer allocator.free(expr);
        try bw.print("    return {s};\n", .{expr});
    } else if (outputs.len > 1) {
        try bw.writeAll("    return .{\n");
        for (outputs) |o| {
            const expr = (try ctx.resolveInput(allocator, o, "value")) orelse return error.DanglingPin;
            defer allocator.free(expr);
            const field = try sanitizeSymbol(allocator, o.kind.Output.name);
            defer allocator.free(field);
            try bw.print("        .{s} = {s},\n", .{ field, expr });
        }
        try bw.writeAll("    };\n");
    }

    const body = try body_aw.toOwnedSlice();
    defer allocator.free(body);

    // `game` is the only fixed parameter of a `.subgraph` entry —
    // discard it when unreferenced.
    if (!mentionsIdent(body, "game")) try w.writeAll("    _ = game;\n");

    try w.writeAll(body);
    try w.writeAll("}\n");
}

/// Render an `OnEvent` flow.
///
/// The handler is a hook-handler-struct method (`FlowEventHandler`)
/// named after the event's qualified tag (`box2d.collision_begin` →
/// `box2d__collision_begin`). The method takes `(self: *@This(),
/// payload: <PayloadType>)`; the payload type comes from
/// `@FieldType(game.PluginEvents, "<qualified_tag>")` against the
/// assembler's resolver (RFC-PLUGIN-EVENTS phase 1). `game` is reachable
/// through `self.game_ptr` (the field-injection convention every
/// shipped engine hook handler already follows —
/// `labelle-engine/src/game.zig:419-429`), so entity-scoped nodes
/// (`GetComponent` / `SetField`) and `Subflow` nodes work in a
/// new-form flow the same way they do in a lifecycle flow. The entity
/// input pin (RFC §9) is mandatory — there is no lifecycle `entity` to
/// fall back on.
///
/// The v1 legacy form (`module` + `callback` + `params`) was removed
/// in RFC-PLUGIN-EVENTS phase 6 (flow-codegen#13); a `.flow.jsonc` with
/// the retired keys now fails to parse in `flow_io.buildEvent`.
fn renderEventEntry(
    allocator: std.mem.Allocator,
    w: *std.Io.Writer,
    flow: flow_io.Flow,
    registry: *const FlowRegistry,
    custom_nodes: ?*const CustomNodeRegistry,
    flow_name: []const u8,
) (CodegenError || std.mem.Allocator.Error || std.Io.Writer.Error)!void {
    var ctx = try GraphContext.init(allocator, flow, registry, custom_nodes);
    defer ctx.deinit();
    // Gate-state vars in an OnEvent entry flow are namespaced by its entry
    // function name (`setup`) — see `gateFlowFn` / `emitGate`.
    ctx.flow_fn = entryFunctionName(flow.event);

    // `name` is `?[]const u8` (RFC-FLOW-VOCABULARY §3 — the field is
    // optional so an `Event` *node* can carry the trigger name; the
    // loader's `buildFlow` already populated it either from the header
    // or the synthesized node, and the empty-name case is rejected
    // upstream). The unwrap reaches the resolved name unconditionally.
    return renderNewFormEventEntry(allocator, w, flow, &ctx, flow_name, flow.event.OnEvent.name.?);
}

/// Map a dotted event name (`box2d.collision_begin`) to the qualified
/// variant tag (`box2d__collision_begin`) the assembler emits in its
/// `PluginEvents` union (labelle-assembler#174 — RFC-PLUGIN-EVENTS phase
/// 1). The mapping is mechanical (replace `.` with `__`) and matches
/// the codegen at `labelle-assembler/src/main_zig.zig:525` —
/// `_entry.name ++ "__" ++ _d.name`. A name with no `.` is treated as a
/// game event (declared in `events/*.zig`) and round-trips verbatim,
/// matching the way `GameEvents` variant names are emitted bare.
///
/// Caller owns the returned bytes.
fn qualifiedTagFromDotted(allocator: std.mem.Allocator, dotted: []const u8) ![]u8 {
    const out = try allocator.alloc(u8, dotted.len + countByte(dotted, '.'));
    var i: usize = 0;
    for (dotted) |c| {
        if (c == '.') {
            out[i] = '_';
            out[i + 1] = '_';
            i += 2;
        } else {
            out[i] = c;
            i += 1;
        }
    }
    return out;
}

/// Render the new-form `OnEvent` flow (RFC-PLUGIN-EVENTS §7, phase 3).
///
/// Emits a `pub const FlowEventHandler = struct { game_ptr: *anyopaque =
/// undefined, pub fn <qualified_tag>(self: *@This(), payload: ...) void
/// { ... } };` whose payload type is reflected from
/// `@FieldType(game_mod.PluginEvents, "<qualified_tag>")`. The
/// assembler discovers this struct in scanner-sorted order and appends
/// `*FlowEventHandler` to the `GameHooks` receiver tuple (phase 4 —
/// labelle-assembler#175, not in scope here). The engine's existing
/// `setHooks` loop (`labelle-engine/src/game.zig:419-429`) injects the
/// `*AssembledGame` pointer into `self.game_ptr` at init.
///
/// The handler body is the same topo-sorted lowering lifecycle handlers
/// use — `game` is reachable through the downcast and entity-scoped
/// nodes resolve their `entity` input pin (RFC §9, the entity-pin
/// scaffold from `8e7fb7b`). No lifecycle `entity` fallback: every
/// entity-scoped node must wire its `entity` pin explicitly, since a
/// new-form OnEvent flow has no "the entity" — entity ids ride the
/// payload.
fn renderNewFormEventEntry(
    allocator: std.mem.Allocator,
    w: *std.Io.Writer,
    flow: flow_io.Flow,
    ctx: *GraphContext,
    flow_name: []const u8,
    dotted_name: []const u8,
) (CodegenError || std.mem.Allocator.Error || std.Io.Writer.Error)!void {
    // Entity-scoped nodes inside a new-form flow MUST wire the entity
    // pin (RFC §9 — "the entity pin is mandatory; no lifecycle `entity`
    // fallback"). A new-form flow has `game` reachable through
    // `game_ptr` but no in-scope `entity` identifier, so an unwired
    // entity pin is the same `DanglingPin` case `assertEntityAvailable`
    // already raises for `.subgraph` entries and `Subflow` subgraphs.
    try assertEntityAvailable(flow);

    // Collect every in-graph `Event` node — by document order — so a
    // multi-trigger flow (RFC-FLOW-VOCABULARY §3 — "A flow with multiple
    // Event nodes is a multi-trigger flow", resolves RFC open question
    // O2) emits one `FlowEventHandler` method per trigger sharing a
    // common downstream-body helper.
    //
    // For the legacy header path (no Event nodes, `event:` carries the
    // trigger), we fall back to the single passed-in `dotted_name`.
    var trigger_names: std.ArrayList([]const u8) = .empty;
    defer trigger_names.deinit(allocator);
    for (flow.nodes) |n| {
        if (n.kind == .Event) try trigger_names.append(allocator, n.kind.Event.name);
    }
    if (trigger_names.items.len == 0) try trigger_names.append(allocator, dotted_name);

    // Header — flow files compile in isolation, so the import of
    // `PluginEvents` rides through the same `game_mod` (`@import("game")`)
    // shim the existing `Game`/`EntityId` decls do. The shim re-export
    // is the phase-3 assembler-side change paired with this codegen.
    try w.writeAll("const PluginEvents = game_mod.PluginEvents;\n\n");

    // Single-trigger flow (the established shape): keep one `__EvPayload`
    // alias and inline the topo-sorted body into the single dispatch
    // method, where `payload` is in scope. This preserves the existing
    // single-event tests + the bouncing-ball codegen byte-for-byte.
    if (trigger_names.items.len == 1) {
        const qualified = try qualifiedTagFromDotted(allocator, trigger_names.items[0]);
        defer allocator.free(qualified);

        // Reflect the payload type through `@FieldType(...)`. The compiler
        // catches an unknown tag here — a flow naming `frobnitz.foo` when
        // no plugin declares it surfaces as a build-time error against the
        // `PluginEvents` field set, not a missing-key in a sidecar.
        try w.print(
            "const __EvPayload = @FieldType(PluginEvents, \"{s}\");\n\n",
            .{qualified},
        );

        try w.writeAll("pub const FlowEventHandler = struct {\n");
        try w.writeAll("    game_ptr: *anyopaque = undefined,\n\n");

        try w.print(
            "    pub fn {s}(self: *@This(), payload: __EvPayload) void {{\n",
            .{qualified},
        );

        try w.writeAll("        const game: *Game = @ptrCast(@alignCast(self.game_ptr));\n");

        // Render the body to a buffer so we can detect which of the fixed
        // parameters (`game`, `payload`) the topo-sorted node bodies
        // actually mention. Zig 0.16 rejects both an unused parameter
        // *and* a pointless `_ = x;` discard of a used one — the buffer
        // pattern is the same one `renderEntryFunction` already uses.
        var body_aw: std.Io.Writer.Allocating = .init(allocator);
        errdefer body_aw.deinit();
        try emitBody(allocator, &body_aw.writer, ctx, flow_name, true);
        const body = try body_aw.toOwnedSlice();
        defer allocator.free(body);

        // Discard the param/binding when the body never reads it.
        if (!mentionsIdent(body, "game")) try w.writeAll("        _ = game;\n");
        if (!mentionsIdent(body, "payload")) try w.writeAll("        _ = payload;\n");

        try indentBlock(w, body, "    ");
        try w.writeAll("    }\n");
        try w.writeAll("};\n");
        return;
    }

    // Multi-trigger flow — one `FlowEventHandler` struct, one `pub fn`
    // per Event node, each method dispatching to a shared `bodyImpl`
    // helper that runs the topo-sorted downstream node bodies (RFC §3,
    // open question O2). Per-event payload aliases (`__EvPayload_<tag>`)
    // keep each method's signature accurate against `PluginEvents`; the
    // helper takes only `game` because the shared body cannot bind to a
    // single payload shape across distinct triggers.
    //
    // De-duplicate trigger names — a flow declaring the same event on
    // two nodes is a structural duplicate (one method per event variant
    // is what `MergeHooks.emit` dispatches against; emitting it twice
    // would be a duplicate decl). `qualified_seen` is a name set;
    // `qualified_storage` keeps the appearance order so the emitted
    // method order matches the document order.
    var qualified_seen: std.StringHashMap(void) = .init(allocator);
    defer qualified_seen.deinit();
    var qualified_storage: std.ArrayList([]u8) = .empty;
    defer {
        for (qualified_storage.items) |q| allocator.free(q);
        qualified_storage.deinit(allocator);
    }
    for (trigger_names.items) |dotted| {
        const q = try qualifiedTagFromDotted(allocator, dotted);
        const gop = try qualified_seen.getOrPut(q);
        if (gop.found_existing) {
            allocator.free(q);
            continue;
        }
        try qualified_storage.append(allocator, q);
    }

    // Per-event payload alias — `__EvPayload_<qualified>`. Same
    // `@FieldType` reflection as the single-event path; the compiler
    // catches an unknown tag against the `PluginEvents` field set.
    for (qualified_storage.items) |q| {
        try w.print(
            "const __EvPayload_{s} = @FieldType(PluginEvents, \"{s}\");\n",
            .{ q, q },
        );
    }
    try w.writeAll("\n");

    try w.writeAll("pub const FlowEventHandler = struct {\n");
    try w.writeAll("    game_ptr: *anyopaque = undefined,\n\n");

    // One dispatch method per Event node. The body is a discard of the
    // unused `payload` (each method picks one event's payload shape,
    // but the shared body can't bind to a specific one) + a call into
    // `bodyImpl(game)`. Same `*Game` downcast every shipped handler
    // uses (`labelle-engine/src/game.zig:419-429`).
    for (qualified_storage.items) |q| {
        try w.print(
            "    pub fn {s}(self: *@This(), payload: __EvPayload_{s}) void {{\n",
            .{ q, q },
        );
        try w.writeAll("        const game: *Game = @ptrCast(@alignCast(self.game_ptr));\n");
        try w.writeAll("        _ = payload;\n");
        try w.writeAll("        bodyImpl(game);\n");
        try w.writeAll("    }\n\n");
    }

    // `bodyImpl(game: *Game) void` — the shared helper. Takes the
    // already-downcast `*Game` so each dispatch method does the
    // `@ptrCast` once, not the helper itself; this also keeps the
    // helper independent of `*anyopaque` so callers outside the struct
    // (the test harness, future opt-in inline-flow inspection) can
    // exercise it directly. `fn` (not `pub fn`) — the helper is a
    // codegen implementation detail.
    var body_aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer body_aw.deinit();
    try emitBody(allocator, &body_aw.writer, ctx, flow_name, true);
    const body = try body_aw.toOwnedSlice();
    defer allocator.free(body);

    try w.writeAll("    fn bodyImpl(game: *Game) void {\n");
    if (!mentionsIdent(body, "game")) try w.writeAll("        _ = game;\n");
    try indentBlock(w, body, "    ");
    try w.writeAll("    }\n");
    try w.writeAll("};\n");
}

/// Emit one subgraph as a `fn` (RFC §6): params → fn args, `Output`
/// nodes → return value, body in topo order.
fn renderSubgraphFunction(
    allocator: std.mem.Allocator,
    w: *std.Io.Writer,
    flow: flow_io.Flow,
    registry: *const FlowRegistry,
    custom_nodes: ?*const CustomNodeRegistry,
) (CodegenError || std.mem.Allocator.Error || std.Io.Writer.Error)!void {
    var ctx = try GraphContext.init(allocator, flow, registry, custom_nodes);
    defer ctx.deinit();

    // A subgraph has no `entity` in scope — only declared params. An
    // entity-scoped node (`GetComponent` / `SetField`) must wire its
    // `entity` input pin (RFC-PLUGIN-EVENTS §9); an unwired one is
    // `DanglingPin` against the offending node. A wired one is fine —
    // the wired expression is what `writeNodeBody` emits as the
    // entity argument.
    try assertEntityAvailable(flow);

    const symbol = try sanitizeSymbol(allocator, flow.name);
    defer allocator.free(symbol);

    // An empty (or all-non-identifier) flow name sanitizes to the bare
    // `_`, which Zig reserves as the discard identifier and rejects as
    // a `fn` name. Such a subgraph passes registry and collision
    // checks yet emits uncompilable `fn _(...)` — reject it up front.
    if (std.mem.eql(u8, symbol, "_")) return error.InvalidFlowName;

    // Gate-state vars in this subgraph are namespaced by its function name
    // (`symbol` == `sanitizeSymbol(flow.name)`), matching `gateFlowFn`'s
    // subgraph branch in the emission pass — see `emitGate`.
    ctx.flow_fn = symbol;

    const outputs = try collectOutputs(allocator, flow);
    defer allocator.free(outputs);

    // Distinct Output names that sanitize to one identifier would emit
    // a result struct with duplicate fields — reject up front.
    try assertNoOutputCollision(allocator, outputs);

    // Multi-output subgraphs return a named result struct (RFC §6).
    // Declare it just above the function so the type is in scope.
    // Output names are sanitized to valid Zig identifiers so a name
    // like `hit-points` or `2nd` still compiles.
    if (outputs.len > 1) {
        try w.print("const {s}_Result = struct {{\n", .{symbol});
        for (outputs) |o| {
            const field = try sanitizeSymbol(allocator, o.kind.Output.name);
            defer allocator.free(field);
            try w.print("    {s}: {s},\n", .{ field, o.kind.Output.type });
        }
        try w.writeAll("};\n");
    }

    // Signature: `fn <symbol>(game: anytype, <param>: <type>, …) <ret> {`
    try w.print("fn {s}(game: anytype", .{symbol});
    try writeParamArgs(allocator, w, flow.params);
    try w.writeAll(") ");
    try writeReturnType(w, symbol, outputs);
    try w.writeAll(" {\n");

    try emitBody(allocator, w, &ctx, flow.name, true);

    // Return statement (RFC §6).
    if (outputs.len == 1) {
        const expr = (try ctx.resolveInput(allocator, outputs[0], "value")) orelse return error.DanglingPin;
        defer allocator.free(expr);
        try w.print("    return {s};\n", .{expr});
    } else if (outputs.len > 1) {
        try w.writeAll("    return .{\n");
        for (outputs) |o| {
            const expr = (try ctx.resolveInput(allocator, o, "value")) orelse return error.DanglingPin;
            defer allocator.free(expr);
            const field = try sanitizeSymbol(allocator, o.kind.Output.name);
            defer allocator.free(field);
            try w.print("        .{s} = {s},\n", .{ field, expr });
        }
        try w.writeAll("    };\n");
    }
    try w.writeAll("}\n");
}

/// Subgraph return type (RFC §6): `void` for zero `Output` nodes, the
/// single output's declared `type` for one, and the generated
/// `<symbol>_Result` struct for many. `Output.type` carries the Zig
/// type (defaulting to `f32` on disk); precise inference through the
/// pin type-system is deferred (RFC open question 2 / #44).
fn writeReturnType(
    w: *std.Io.Writer,
    symbol: []const u8,
    outputs: []const *const flow_io.Node,
) !void {
    if (outputs.len == 0) {
        try w.writeAll("void");
    } else if (outputs.len == 1) {
        try w.writeAll(outputs[0].kind.Output.type);
    } else {
        try w.print("{s}_Result", .{symbol});
    }
}

/// Emit the `pub fn` header for the file entry point. The flow's
/// top-level `params` are appended as fn parameters — same as a
/// subgraph — so `Param` nodes in the entry flow resolve their reads
/// to in-scope identifiers (RFC §3).
///
/// `outputs` is the entry flow's `Output` nodes (empty for lifecycle
/// events, which always return `void`). When non-empty — a `.subgraph`
/// entry — the return type follows the subgraph rule (RFC §6): the
/// single output's `type`, or the `<entry_fn>_Result` struct.
fn writeFnHeader(
    allocator: std.mem.Allocator,
    w: anytype,
    flow: flow_io.Flow,
    outputs: []const *const flow_io.Node,
) !void {
    switch (flow.event) {
        // A subgraph flow used as the file entry point still needs a
        // callable surface — emit `pub fn onCall`.
        .subgraph => try w.writeAll("pub fn onCall(game: anytype"),
        // `OnEvent` flows are emitted by `renderEventEntry`, which
        // never calls this header writer.
        .OnEvent => unreachable,
    }
    try writeParamArgs(allocator, w, flow.params);
    try w.writeAll(") ");
    try writeReturnType(w, entryFunctionName(flow.event), outputs);
    try w.writeAll(" {\n");
}

/// Emit a flow's declared `params` as `fn` arguments — `, <name>:
/// <type>` each. Names are run through `sanitizeSymbol` to a valid
/// Zig identifier (RFC §3); `Param` node reads (see `writeNodeBody`)
/// apply the same sanitization so the emitted identifiers line up.
fn writeParamArgs(
    allocator: std.mem.Allocator,
    w: anytype,
    params: []const flow_io.Param,
) !void {
    for (params) |p| {
        const name = try sanitizeSymbol(allocator, p.name);
        defer allocator.free(name);
        try w.print(", {s}: {s}", .{ name, p.type });
    }
}

/// The `pub fn` name emitted for a flow used as the file entry point,
/// keyed by its `Event`. These four names occupy the file's top-level
/// symbol namespace alongside the subgraph `fn`s.
fn entryFunctionName(event: flow_io.Event) []const u8 {
    return switch (event) {
        .subgraph => "onCall",
        // An `OnEvent` flow's public entry is its `setup` — the
        // registrar the script-runner calls (see `renderEventEntry`).
        .OnEvent => "setup",
    };
}

/// The `<flowfn>` prefix used to namespace a flow's per-node gate state
/// `pub var`s (flow-codegen#47). It is exactly the flow's emitted
/// function-name identifier — `entryFunctionName(event)` for the file
/// entry flow, `sanitizeSymbol(name)` for a subgraph — i.e. the same
/// identifiers `assertNoSymbolCollision` proves unique across the file.
/// `emitGate` reads the same value off `ctx.flow_fn`, so the emission and
/// lowering sites produce byte-identical var names. Caller owns the
/// returned bytes.
fn gateFlowFn(
    allocator: std.mem.Allocator,
    flow: flow_io.Flow,
    is_entry: bool,
) std.mem.Allocator.Error![]u8 {
    if (is_entry) return allocator.dupe(u8, entryFunctionName(flow.event));
    return sanitizeSymbol(allocator, flow.name);
}

/// Emit the module-level deferred-subflow state for one `Delay` node
/// (flow-codegen#48): a capture struct holding a snapshot of the deferred
/// Subflow's input arguments, plus a trampoline `fn` the scheduler invokes
/// when the timer fires.
///
/// Shape (namespaced by `<flowfn>` — the flow's function name — so two
/// Delays at the same node id in different flows get distinct decls):
///   const __DelayCap_<flowfn>_n<id> = struct { <arg0>: <type0>, … };
///   fn __delay_tramp_<flowfn>_n<id>(game_ctx: *anyopaque, ctx: *anyopaque) void {
///       const game: *Game = @ptrCast(@alignCast(game_ctx));
///       const cap: *__DelayCap_<flowfn>_n<id> = @ptrCast(@alignCast(ctx));
///       _ = <subflow_symbol>(game, cap.<arg0>, …);  // `_ =` only if it returns
///   }
/// The capture FIELDS are the referenced flow's declared input params
/// (names sanitized to valid Zig identifiers, in declared order); the
/// trampoline forwards them positionally to the subflow function. The
/// scheduler OWNS and frees the capture (labelle-engine#605), so the
/// trampoline never frees `ctx`. `game` is the concrete `*Game` already in
/// scope via the module's `@import("game")` shim — the subflow takes
/// `game: anytype` and is called with that `*Game`-shaped value.
fn emitDelayState(
    allocator: std.mem.Allocator,
    w: *std.Io.Writer,
    flow: flow_io.Flow,
    registry: *const FlowRegistry,
    flow_fn: []const u8,
    node: flow_io.Node,
) (CodegenError || std.mem.Allocator.Error || std.Io.Writer.Error)!void {
    const target = delaySubflowNode(flow, node.id) orelse return error.MalformedFlow;
    const ref = registry.get(target.kind.Subflow.flow) orelse return error.UnknownFlowRef;
    const symbol = try sanitizeSymbol(allocator, ref.name);
    defer allocator.free(symbol);

    // Capture struct — one field per declared input param of the deferred
    // subflow, names sanitized so a param like `hit-points` still emits a
    // valid Zig field identifier. A subflow with no params yields an empty
    // struct (a valid zero-field capture).
    try w.print("const __DelayCap_{s}_n{d} = struct {{", .{ flow_fn, node.id });
    for (ref.params, 0..) |p, i| {
        const field = try sanitizeSymbol(allocator, p.name);
        defer allocator.free(field);
        if (i != 0) try w.writeAll(",");
        try w.print(" {s}: {s}", .{ field, p.type });
    }
    if (ref.params.len != 0) try w.writeAll(" ");
    try w.writeAll("};\n");

    // Trampoline — cast both type-erased pointers back, then forward the
    // snapshotted args to the subflow. A void subgraph (no `Output` nodes)
    // is a bare call statement; a value-producing one is discarded with
    // `_ =` so the trampoline stays `void`-returning.
    try w.print(
        "fn __delay_tramp_{s}_n{d}(game_ctx: *anyopaque, ctx: *anyopaque) void {{\n",
        .{ flow_fn, node.id },
    );
    try w.writeAll("    const game: *Game = @ptrCast(@alignCast(game_ctx));\n");
    try w.print(
        "    const cap: *__DelayCap_{s}_n{d} = @ptrCast(@alignCast(ctx));\n",
        .{ flow_fn, node.id },
    );
    // Silence "unused" when the capture is empty / the subflow takes no
    // params and discards nothing readable: `cap` is still referenced via
    // its field reads below when params exist; for the zero-param case it
    // would be unused, so discard it explicitly.
    if (ref.params.len == 0) try w.writeAll("    _ = cap;\n");

    const ref_void = !anyOutput(ref.nodes);
    if (ref_void) {
        try w.print("    {s}(game", .{symbol});
    } else {
        try w.print("    _ = {s}(game", .{symbol});
    }
    for (ref.params) |p| {
        const field = try sanitizeSymbol(allocator, p.name);
        defer allocator.free(field);
        try w.print(", cap.{s}", .{field});
    }
    try w.writeAll(");\n");
    try w.writeAll("}\n");
}

/// Reject the case where two file-level symbols with distinct effective
/// names sanitize to the same Zig identifier — that would emit two
/// definitions with the same symbol and fail to compile
/// (CodegenError.SymbolCollision). Covers both the subgraph `fn`s and
/// the entry `pub fn` (`entry_fn_name`): a subgraph whose name
/// sanitizes to e.g. `onCall` collides with the entry handler.
fn assertNoSymbolCollision(
    allocator: std.mem.Allocator,
    entry_fn_name: []const u8,
    subgraphs: []const flow_io.Flow,
) (CodegenError || std.mem.Allocator.Error)!void {
    // Each symbol maps to the source it was emitted from. A subgraph
    // claiming the entry handler's identifier is always a collision —
    // even if its flow name happens to equal `entry_fn_name` — because
    // the entry `pub fn` and a subgraph `fn` are two distinct
    // definitions in one file.
    const Source = union(enum) { entry, subgraph: []const u8 };
    var by_symbol = std.StringHashMap(Source).init(allocator);
    defer {
        var it = by_symbol.iterator();
        while (it.next()) |e| allocator.free(e.key_ptr.*);
        by_symbol.deinit();
    }
    // Seed with the entry `pub fn` name. It is already a valid Zig
    // identifier, so it equals its own sanitized form.
    {
        const seed = try allocator.dupe(u8, entry_fn_name);
        const gop = try by_symbol.getOrPut(seed);
        if (gop.found_existing) allocator.free(seed) else gop.value_ptr.* = .entry;
    }
    for (subgraphs) |sg| {
        const symbol = try sanitizeSymbol(allocator, sg.name);
        const gop = try by_symbol.getOrPut(symbol);
        if (gop.found_existing) {
            allocator.free(symbol);
            switch (gop.value_ptr.*) {
                // Colliding with the entry handler is always fatal.
                .entry => return error.SymbolCollision,
                // Same subgraph name twice is fine (registry de-dups);
                // only a distinct name colliding is an error.
                .subgraph => |prev| if (!std.mem.eql(u8, prev, sg.name))
                    return error.SymbolCollision,
            }
        } else {
            gop.value_ptr.* = .{ .subgraph = sg.name };
        }
    }
}

/// `seen.put` with an allocator-owned copy of `name` as the key,
/// freeing the copy when the key already exists. Keys are freed by
/// the caller's `keyIterator` loop on cleanup.
fn putOwnedKey(
    allocator: std.mem.Allocator,
    seen: *std.StringHashMap(void),
    name: []const u8,
) std.mem.Allocator.Error!void {
    const key = try allocator.dupe(u8, name);
    const gop = try seen.getOrPut(key);
    if (gop.found_existing) allocator.free(key);
}

/// Reject a flow whose declared `params`, after sanitization, collide
/// with each other or with the fixed `game` parameter. Such a flow
/// parses cleanly yet emits a signature with duplicate parameter
/// identifiers, which Zig rejects (`ParamNameCollision`). Post Phase 6
/// (RFC-FLOW-VOCABULARY) the only fixed parameter on every emitted
/// signature is `game` — the lifecycle dt/entity args are gone, and an
/// `OnEvent` handler's payload pins are derived names that don't
/// collide with declared params.
fn assertNoParamCollision(
    allocator: std.mem.Allocator,
    flow: flow_io.Flow,
) (CodegenError || std.mem.Allocator.Error)!void {
    var seen = std.StringHashMap(void).init(allocator);
    defer {
        var it = seen.keyIterator();
        while (it.next()) |k| allocator.free(k.*);
        seen.deinit();
    }

    try putOwnedKey(allocator, &seen, "game");

    for (flow.params) |p| {
        const name = try sanitizeSymbol(allocator, p.name);
        const gop = try seen.getOrPut(name);
        if (gop.found_existing) {
            allocator.free(name);
            return error.ParamNameCollision;
        }
    }
}

/// True when `node` is entity-scoped and has no incoming edge on its
/// optional `entity` input pin (RFC-PLUGIN-EVENTS §9). In a context
/// where no `entity` identifier is in scope (a `.subgraph` entry or a
/// `Subflow`-referenced subgraph), this is the per-node `DanglingPin`
/// signal — the v1 blanket-rejection refined to a node-level check.
fn entityScopedAndUnwired(flow: flow_io.Flow, node: flow_io.Node) bool {
    switch (node.kind) {
        .GetComponent, .SetField => {},
        else => return false,
    }
    for (flow.edges) |e| {
        if (e.to.node == node.id and std.mem.eql(u8, e.to.pin, "entity")) return false;
    }
    return true;
}

/// Reject an entity-scoped node missing both an entity-pin wire and an
/// in-scope `entity` identifier (RFC-PLUGIN-EVENTS §9). Called from the
/// `.subgraph` entry path and `renderSubgraphFunction` — both contexts
/// where `entity` is not a function parameter. Returns `DanglingPin`
/// against the first offending node so the diagnostic points at a
/// specific `.flow.jsonc` location, per the RFC §9 per-node check that
/// lets a flow mix wired and unwired entity-scoped nodes freely.
fn assertEntityAvailable(flow: flow_io.Flow) CodegenError!void {
    for (flow.nodes) |n| {
        if (entityScopedAndUnwired(flow, n)) return error.DanglingPin;
    }
}

/// Collect component type names referenced across the entry flow and
/// every subgraph — de-duplicated, alphabetically sorted.
fn collectComponentTypesAll(
    allocator: std.mem.Allocator,
    entry: flow_io.Flow,
    subgraphs: []const flow_io.Flow,
) (CodegenError || std.mem.Allocator.Error)![][]const u8 {
    var seen = std.StringHashMap(void).init(allocator);
    defer seen.deinit();
    var list: std.ArrayList([]const u8) = .empty;
    errdefer list.deinit(allocator);

    try collectComponentTypesInto(entry, &seen, &list, allocator);
    for (subgraphs) |sg| {
        try collectComponentTypesInto(sg, &seen, &list, allocator);
    }

    const out = try list.toOwnedSlice(allocator);
    std.mem.sort([]const u8, out, {}, struct {
        fn lt(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.lessThan(u8, a, b);
        }
    }.lt);
    return out;
}

fn collectComponentTypesInto(
    flow: flow_io.Flow,
    seen: *std.StringHashMap(void),
    list: *std.ArrayList([]const u8),
    allocator: std.mem.Allocator,
) (CodegenError || std.mem.Allocator.Error)!void {
    for (flow.nodes) |n| {
        const type_name: ?[]const u8 = switch (n.kind) {
            .GetComponent => |b| b.type,
            .SetField => |b| blk: {
                const dot = std.mem.lastIndexOfScalar(u8, b.target, '.') orelse break :blk null;
                break :blk b.target[0..dot];
            },
            else => null,
        };
        if (type_name) |t| {
            if (t.len == 0) continue;
            if (std.mem.indexOfScalar(u8, t, '.') != null) return error.NamespacedComponentType;
            const gop = try seen.getOrPut(t);
            if (!gop.found_existing) try list.append(allocator, t);
        }
    }
}
